[prune]
  non-go = true
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/mattermost/mattermost-server"
  branch = "release-5.4"

[[constraint]]
  name = "github.com/blang/semver"
  version = "~3.5.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "~1.2.0"
